/* ==========================================================================
   Toy Haven - data.js
   Single source of truth for the product catalogue.
   The catalogue is a plain JSON array so it can be swapped for a real API
   response later without touching any rendering code.
   ========================================================================== */

/** Product categories used by the filter controls and the navigation. */
const TH_CATEGORIES = [
  { slug: "all", label: "All products" },
  { slug: "figurines", label: "Figurines" },
  { slug: "toys", label: "Toys" },
  { slug: "board-games", label: "Board Games" },
  { slug: "diecast", label: "Diecast Cars" }
];

/** @type {Array<Object>} The Toy Haven product catalogue. */
const TH_PRODUCTS = [
  {
    "id": "fig-01",
    "name": "Nova Sentinel Guardian",
    "category": "figurines",
    "categoryLabel": "Figurines",
    "price": 34.99,
    "brand": "Orbit Forge",
    "ageRange": "14+",
    "material": "PVC & ABS",
    "specLabel": "Scale",
    "spec": "1:10 scale",
    "rating": 4.8,
    "reviews": 214,
    "tag": "Best Seller",
    "description": "A hand-painted guardian of the outer colonies, posed mid-stride with a magnetic cape and three swappable hands.",
    "image": "assets/img/products/fig-01.webp",
    "alt": "Nova Sentinel Guardian figurine illustration",
    "inStock": true
  },
  {
    "id": "fig-02",
    "name": "Ember Blade Duelist",
    "category": "figurines",
    "categoryLabel": "Figurines",
    "price": 42.5,
    "brand": "Orbit Forge",
    "ageRange": "14+",
    "material": "PVC & ABS",
    "specLabel": "Scale",
    "spec": "1:10 scale",
    "rating": 4.7,
    "reviews": 168,
    "tag": "New",
    "description": "A duelist cast in molten reds, packed with two katana sculpts and a translucent flame effect part.",
    "image": "assets/img/products/fig-02.webp",
    "alt": "Ember Blade Duelist figurine illustration",
    "inStock": true
  },
  {
    "id": "fig-03",
    "name": "Deep Sea Cartographer",
    "category": "figurines",
    "categoryLabel": "Figurines",
    "price": 29.0,
    "brand": "Tidewell Studio",
    "ageRange": "12+",
    "material": "Resin",
    "specLabel": "Scale",
    "spec": "1:12 scale",
    "rating": 4.5,
    "reviews": 96,
    "tag": "",
    "description": "A lantern-lit explorer with a removable diving helmet and a fold-out map accessory.",
    "image": "assets/img/products/fig-03.webp",
    "alt": "Deep Sea Cartographer figurine illustration",
    "inStock": true
  },
  {
    "id": "fig-04",
    "name": "Clockwork Alchemist",
    "category": "figurines",
    "categoryLabel": "Figurines",
    "price": 47.9,
    "brand": "Tidewell Studio",
    "ageRange": "14+",
    "material": "Resin & brass",
    "specLabel": "Scale",
    "spec": "1:10 scale",
    "rating": 4.9,
    "reviews": 311,
    "tag": "Limited",
    "description": "Brass-finished gears turn on the backpack of this alchemist, finished with a hand-applied patina wash.",
    "image": "assets/img/products/fig-04.webp",
    "alt": "Clockwork Alchemist figurine illustration",
    "inStock": true
  },
  {
    "id": "fig-05",
    "name": "Aurora Sky Ranger",
    "category": "figurines",
    "categoryLabel": "Figurines",
    "price": 38.25,
    "brand": "Orbit Forge",
    "ageRange": "12+",
    "material": "PVC",
    "specLabel": "Scale",
    "spec": "1:12 scale",
    "rating": 4.4,
    "reviews": 74,
    "tag": "",
    "description": "Iridescent wings catch the light from every angle; includes a clear flight stand and two head sculpts.",
    "image": "assets/img/products/fig-05.webp",
    "alt": "Aurora Sky Ranger figurine illustration",
    "inStock": true
  },
  {
    "id": "fig-06",
    "name": "Moss Grove Wanderer",
    "category": "figurines",
    "categoryLabel": "Figurines",
    "price": 26.75,
    "brand": "Tidewell Studio",
    "ageRange": "10+",
    "material": "PVC",
    "specLabel": "Scale",
    "spec": "1:14 scale",
    "rating": 4.3,
    "reviews": 58,
    "tag": "",
    "description": "A woodland traveller with a fabric-effect cloak, sculpted moss base and a tiny companion beetle.",
    "image": "assets/img/products/fig-06.webp",
    "alt": "Moss Grove Wanderer figurine illustration",
    "inStock": true
  },
  {
    "id": "toy-01",
    "name": "Cosmo Launch Rocket",
    "category": "toys",
    "categoryLabel": "Toys",
    "price": 24.99,
    "brand": "Playloop",
    "ageRange": "4+",
    "material": "Recycled ABS",
    "specLabel": "Contents",
    "spec": "3 modules",
    "rating": 4.6,
    "reviews": 402,
    "tag": "Best Seller",
    "description": "A three-stage rocket that clicks apart into a launch pad, capsule and rover for open-ended play.",
    "image": "assets/img/products/toy-01.webp",
    "alt": "Cosmo Launch Rocket toy illustration",
    "inStock": true
  },
  {
    "id": "toy-02",
    "name": "Rainbow Stacker Tower",
    "category": "toys",
    "categoryLabel": "Toys",
    "price": 18.5,
    "brand": "Playloop",
    "ageRange": "2+",
    "material": "FSC beech wood",
    "specLabel": "Contents",
    "spec": "12 pieces",
    "rating": 4.8,
    "reviews": 529,
    "tag": "",
    "description": "Chunky, sanded-smooth blocks in a graded palette that teach ordering, balance and colour naming.",
    "image": "assets/img/products/toy-02.webp",
    "alt": "Rainbow Stacker Tower toy illustration",
    "inStock": true
  },
  {
    "id": "toy-03",
    "name": "Bramble the Bear",
    "category": "toys",
    "categoryLabel": "Toys",
    "price": 21.0,
    "brand": "Hugsmith",
    "ageRange": "0+",
    "material": "Organic cotton plush",
    "specLabel": "Contents",
    "spec": "32 cm tall",
    "rating": 4.9,
    "reviews": 873,
    "tag": "Top Rated",
    "description": "A weighted-bottom plush bear with embroidered eyes, machine washable and hypoallergenic.",
    "image": "assets/img/products/toy-03.webp",
    "alt": "Bramble the Bear toy illustration",
    "inStock": true
  },
  {
    "id": "toy-04",
    "name": "Star Cadet Shuttle",
    "category": "toys",
    "categoryLabel": "Toys",
    "price": 32.4,
    "brand": "Playloop",
    "ageRange": "5+",
    "material": "Recycled ABS",
    "specLabel": "Contents",
    "spec": "4 modules",
    "rating": 4.4,
    "reviews": 187,
    "tag": "",
    "description": "Glow-in-the-dark shuttle with a hinged cargo bay, retractable ramp and two cadet mini-figures.",
    "image": "assets/img/products/toy-04.webp",
    "alt": "Star Cadet Shuttle toy illustration",
    "inStock": true
  },
  {
    "id": "toy-05",
    "name": "Meadow Block Set",
    "category": "toys",
    "categoryLabel": "Toys",
    "price": 27.8,
    "brand": "Playloop",
    "ageRange": "3+",
    "material": "FSC beech wood",
    "specLabel": "Contents",
    "spec": "18 pieces",
    "rating": 4.5,
    "reviews": 241,
    "tag": "New",
    "description": "Arches, half-moons and slotted panels that combine into bridges, barns and anything else in reach.",
    "image": "assets/img/products/toy-05.webp",
    "alt": "Meadow Block Set toy illustration",
    "inStock": true
  },
  {
    "id": "toy-06",
    "name": "Pippin the Fox",
    "category": "toys",
    "categoryLabel": "Toys",
    "price": 19.6,
    "brand": "Hugsmith",
    "ageRange": "0+",
    "material": "Organic cotton plush",
    "specLabel": "Contents",
    "spec": "28 cm tall",
    "rating": 4.7,
    "reviews": 364,
    "tag": "",
    "description": "A soft-brushed fox with a curled tail, safety-stitched features and a gentle rattle in one paw.",
    "image": "assets/img/products/toy-06.webp",
    "alt": "Pippin the Fox toy illustration",
    "inStock": true
  },
  {
    "id": "bg-01",
    "name": "Harbour Trade Routes",
    "category": "board-games",
    "categoryLabel": "Board Games",
    "price": 44.0,
    "brand": "Northlight Games",
    "ageRange": "10+",
    "material": "Linen-finish card",
    "specLabel": "Players",
    "spec": "2-4 players",
    "rating": 4.8,
    "reviews": 318,
    "tag": "Best Seller",
    "description": "Claim docks, ship cargo and out-plan your rivals across a modular harbour that changes every game.",
    "image": "assets/img/products/bg-01.webp",
    "alt": "Harbour Trade Routes board game illustration",
    "inStock": true
  },
  {
    "id": "bg-02",
    "name": "Sundown Express",
    "category": "board-games",
    "categoryLabel": "Board Games",
    "price": 36.9,
    "brand": "Northlight Games",
    "ageRange": "8+",
    "material": "Linen-finish card",
    "specLabel": "Players",
    "spec": "2-5 players",
    "rating": 4.6,
    "reviews": 205,
    "tag": "",
    "description": "A light-hearted route builder where every carriage you add makes the timetable harder to keep.",
    "image": "assets/img/products/bg-02.webp",
    "alt": "Sundown Express board game illustration",
    "inStock": true
  },
  {
    "id": "bg-03",
    "name": "Cavern of Echoes",
    "category": "board-games",
    "categoryLabel": "Board Games",
    "price": 52.25,
    "brand": "Lantern & Loom",
    "ageRange": "12+",
    "material": "Card & resin",
    "specLabel": "Players",
    "spec": "1-4 players",
    "rating": 4.9,
    "reviews": 412,
    "tag": "Limited",
    "description": "A cooperative dungeon crawl with a rotating cave board and a solo mode built in from the start.",
    "image": "assets/img/products/bg-03.webp",
    "alt": "Cavern of Echoes board game illustration",
    "inStock": true
  },
  {
    "id": "bg-04",
    "name": "Petal Market",
    "category": "board-games",
    "categoryLabel": "Board Games",
    "price": 28.4,
    "brand": "Lantern & Loom",
    "ageRange": "7+",
    "material": "Linen-finish card",
    "specLabel": "Players",
    "spec": "2-4 players",
    "rating": 4.4,
    "reviews": 143,
    "tag": "New",
    "description": "Fill flower orders, trade for the stems you need and try not to hand your neighbour the winning bouquet.",
    "image": "assets/img/products/bg-04.webp",
    "alt": "Petal Market board game illustration",
    "inStock": true
  },
  {
    "id": "bg-05",
    "name": "Signal Fire",
    "category": "board-games",
    "categoryLabel": "Board Games",
    "price": 41.75,
    "brand": "Northlight Games",
    "ageRange": "10+",
    "material": "Card & wood",
    "specLabel": "Players",
    "spec": "3-6 players",
    "rating": 4.5,
    "reviews": 176,
    "tag": "",
    "description": "A hidden-role game of beacons and bluffs that plays in under forty minutes.",
    "image": "assets/img/products/bg-05.webp",
    "alt": "Signal Fire board game illustration",
    "inStock": true
  },
  {
    "id": "bg-06",
    "name": "Tidepool Naturalist",
    "category": "board-games",
    "categoryLabel": "Board Games",
    "price": 33.1,
    "brand": "Lantern & Loom",
    "ageRange": "8+",
    "material": "Card & wood",
    "specLabel": "Players",
    "spec": "1-4 players",
    "rating": 4.7,
    "reviews": 229,
    "tag": "",
    "description": "Draft creatures, build a coastline and score the quiet, careful engine you have been assembling all game.",
    "image": "assets/img/products/bg-06.webp",
    "alt": "Tidepool Naturalist board game illustration",
    "inStock": true
  },
  {
    "id": "dc-01",
    "name": "Vantage GT Coupe",
    "category": "diecast",
    "categoryLabel": "Diecast Cars",
    "price": 22.99,
    "brand": "Apex Line",
    "ageRange": "8+",
    "material": "Zinc alloy",
    "specLabel": "Scale",
    "spec": "1:24 scale",
    "rating": 4.7,
    "reviews": 296,
    "tag": "Best Seller",
    "description": "A low-slung grand tourer with opening doors, a detailed cabin and rubber-compound tyres.",
    "image": "assets/img/products/dc-01.webp",
    "alt": "Vantage GT Coupe diecast car illustration",
    "inStock": true
  },
  {
    "id": "dc-02",
    "name": "Rally 04 Homologation",
    "category": "diecast",
    "categoryLabel": "Diecast Cars",
    "price": 26.4,
    "brand": "Apex Line",
    "ageRange": "8+",
    "material": "Zinc alloy",
    "specLabel": "Scale",
    "spec": "1:24 scale",
    "rating": 4.6,
    "reviews": 184,
    "tag": "",
    "description": "Mud-flecked livery, a roof scoop and a fully wired engine bay under the lifting bonnet.",
    "image": "assets/img/products/dc-02.webp",
    "alt": "Rally 04 Homologation diecast car illustration",
    "inStock": true
  },
  {
    "id": "dc-03",
    "name": "City Transit Bus",
    "category": "diecast",
    "categoryLabel": "Diecast Cars",
    "price": 31.2,
    "brand": "Apex Line",
    "ageRange": "6+",
    "material": "Zinc alloy",
    "specLabel": "Scale",
    "spec": "1:32 scale",
    "rating": 4.3,
    "reviews": 112,
    "tag": "",
    "description": "Twin doors that slide open, a printed route board and forty individually moulded seats.",
    "image": "assets/img/products/dc-03.webp",
    "alt": "City Transit Bus diecast car illustration",
    "inStock": true
  },
  {
    "id": "dc-04",
    "name": "Heritage Roadster 1962",
    "category": "diecast",
    "categoryLabel": "Diecast Cars",
    "price": 29.85,
    "brand": "Marque Classics",
    "ageRange": "10+",
    "material": "Zinc alloy",
    "specLabel": "Scale",
    "spec": "1:24 scale",
    "rating": 4.8,
    "reviews": 258,
    "tag": "Top Rated",
    "description": "Wire-effect wheels, a folded soft top and chrome trim applied by hand after painting.",
    "image": "assets/img/products/dc-04.webp",
    "alt": "Heritage Roadster 1962 diecast car illustration",
    "inStock": true
  },
  {
    "id": "dc-05",
    "name": "Circuit Prototype 9",
    "category": "diecast",
    "categoryLabel": "Diecast Cars",
    "price": 34.6,
    "brand": "Marque Classics",
    "ageRange": "10+",
    "material": "Zinc alloy & resin",
    "specLabel": "Scale",
    "spec": "1:24 scale",
    "rating": 4.5,
    "reviews": 151,
    "tag": "New",
    "description": "An endurance prototype with a removable rear cover and race-accurate number decals.",
    "image": "assets/img/products/dc-05.webp",
    "alt": "Circuit Prototype 9 diecast car illustration",
    "inStock": true
  },
  {
    "id": "dc-06",
    "name": "Alpine Recovery Truck",
    "category": "diecast",
    "categoryLabel": "Diecast Cars",
    "price": 27.5,
    "brand": "Marque Classics",
    "ageRange": "6+",
    "material": "Zinc alloy",
    "specLabel": "Scale",
    "spec": "1:32 scale",
    "rating": 4.4,
    "reviews": 98,
    "tag": "",
    "description": "A working winch, tilting flatbed and amber beacon lights on a rugged alpine chassis.",
    "image": "assets/img/products/dc-06.webp",
    "alt": "Alpine Recovery Truck diecast car illustration",
    "inStock": true
  }
];
